import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { adminChatId, inlineButton, inlineKeyboard, registerMainMenuItem, requireOwner } from "../toolkit/index.js";
import { findOrder, findTicket, now, orders, products, saveOrder, saveProduct, saveTicket, tickets, users, type Product } from "../domain.js";

registerMainMenuItem({ label: "⚙️ Управление", data: "admin:open", order: 90 });
const composer = new Composer<Ctx>();
const gate = (ctx: Ctx) => requireOwner(ctx as never);
const panel = inlineKeyboard([[inlineButton("📊 Статистика", "admin:stats"), inlineButton("🛒 Заказы", "admin:orders")], [inlineButton("💰 Товары и цены", "admin:products")], [inlineButton("🆘 Обращения", "admin:tickets"), inlineButton("👥 Пользователи", "admin:users")], [inlineButton("📢 Рассылка", "admin:broadcast")], [inlineButton("⬅️ Назад", "menu:main")]]);

composer.callbackQuery("admin:open", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; await ctx.reply("Панель управления", { reply_markup: panel }); });
composer.callbackQuery("admin:stats", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const [u, o] = await Promise.all([users(ctx), orders(ctx)]); const paid = o.filter((x) => x.status === "completed"); await ctx.reply(`Статистика\nПользователей: ${u.length}\nЗаказов: ${o.length}\nВыручка: ${paid.reduce((sum, x) => sum + x.price, 0)} ₽`, { reply_markup: inlineKeyboard([[inlineButton("⬅️ В панель", "admin:open")]]) }); });
composer.callbackQuery(/^admin:orders(?::(\d+))?$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const page = Number(ctx.callbackQuery.data.split(":")[2] ?? 0); const list = (await orders(ctx)).slice(page * 10, page * 10 + 10); const all = await orders(ctx); const rows = list.map((o) => [inlineButton(`${o.product_id} · ${o.status}`, `admin:order:view:${o.id}`)]); if (page > 0 || all.length > (page + 1) * 10) rows.push([...(page > 0 ? [inlineButton("Назад", `admin:orders:${page - 1}`)] : []), ...(all.length > (page + 1) * 10 ? [inlineButton("Далее", `admin:orders:${page + 1}`)] : [])]); rows.push([inlineButton("⬅️ В панель", "admin:open")]); await ctx.reply(list.length ? "Заказы:" : "Заказов пока нет.", { reply_markup: inlineKeyboard(rows) }); });
composer.callbackQuery(/^admin:order:view:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const o = await findOrder(ctx, ctx.callbackQuery.data.slice("admin:order:view:".length)); if (!o) { await ctx.reply("Не нашли этот заказ."); return; } await ctx.reply(`Заказ ${o.id}\nТовар: ${o.product_id}\nСтатус: ${o.status}\nСумма: ${o.price} ${o.currency}`, { reply_markup: inlineKeyboard([[inlineButton("✅ Проверить оплату", `admin:order:verify:${o.id}`), inlineButton("❌ Отклонить", `admin:order:failed:${o.id}`)], [inlineButton("Завершить", `admin:order:complete:${o.id}`)], [inlineButton("⬅️ К заказам", "admin:orders")]]) }); });
composer.callbackQuery(/^admin:order:(verify|complete|failed):(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const [, action, id] = ctx.callbackQuery.data.split(":"); const o = await findOrder(ctx, id); if (!o) { await ctx.reply("Не нашли этот заказ."); return; } if (action === "verify") { if (o.status !== "awaiting_manual_verification") { await ctx.reply("Сначала покупатель должен подтвердить оплату."); return; } o.status = "verified"; } else if (action === "complete") { if (o.status !== "verified") { await ctx.reply("Сначала подтвердите оплату."); return; } o.status = "completed"; o.paid_at = now(); } else { if (o.status === "completed") { await ctx.reply("Завершённый заказ нельзя отклонить."); return; } o.status = "failed"; } o.updated_at = now(); o.admin_notes.push(`${action} ${now()}`); await saveOrder(ctx, o); try { await ctx.api.sendMessage(o.buyer_id, action === "complete" ? `✅ Заказ завершён.\n${(await products(ctx)).find((p) => p.id === o.product_id)?.delivery_instructions ?? "Инструкции по доставке отправит оператор."}` : action === "verify" ? "✅ Оплата подтверждена. Остался последний шаг — доставка.": "Оплату не удалось подтвердить. Напишите в поддержку, если считаете это ошибкой."); } catch { /* blocked buyer */ } await ctx.reply(action === "complete" ? "Заказ завершён, инструкции отправлены." : action === "verify" ? "Оплата подтверждена." : "Заказ отклонён."); });

composer.callbackQuery("admin:products", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const list = (await products(ctx)).slice(0, 10); await ctx.reply(list.length ? "Товары и цены:\n" + list.map((p) => `${p.name} · ${p.price} ${p.currency}`).join("\n") : "Товаров пока нет.", { reply_markup: inlineKeyboard([...list.map((p) => [inlineButton(`Изменить ${p.id}`, `admin:product:edit:${p.id}`), inlineButton("Удалить", `admin:product:delete:${p.id}`)]), [inlineButton("➕ Создать товар", "admin:product:new")], [inlineButton("⬅️ В панель", "admin:open")]]) }); });
composer.callbackQuery(/^admin:product:(new|edit):?(.*)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const [, action, id] = ctx.callbackQuery.data.split(":"); ctx.session.step = "admin_product_form"; ctx.session.pendingProductEditId = action === "edit" ? id : undefined; await ctx.reply("Отправьте 6 полей через |: название | описание | цена | валюта | доставка | ссылка https://", { reply_markup: { force_reply: true, input_field_placeholder: "Данные товара" } }); });
composer.callbackQuery(/^admin:product:delete:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const p = (await products(ctx)).find((x) => x.id === ctx.callbackQuery.data.split(":")[3]); if (!p) { await ctx.reply("Товар не найден."); return; } p.active = false; p.updated_at = now(); p.admin_notes = [...(p.admin_notes ?? []), `deleted ${now()}`]; await saveProduct(ctx, p); await ctx.reply("Товар отключён.", { reply_markup: inlineKeyboard([[inlineButton("К товарам", "admin:products")]]) }); });

composer.callbackQuery("admin:tickets", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const list = (await tickets(ctx)).slice(0, 10); await ctx.reply(list.length ? "Обращения:" : "Новых обращений нет.", { reply_markup: inlineKeyboard([...list.map((t) => [inlineButton(`Ответить ${t.id}`, `admin:ticket:${t.id}:reply`), inlineButton("Закрыть", `admin:ticket:${t.id}:close`)]), [inlineButton("⬅️ В панель", "admin:open")]]) }); });
composer.callbackQuery(/^admin:ticket:(.+):reply$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; if (!(await findTicket(ctx, ctx.callbackQuery.data.split(":")[2]))) { await ctx.reply("Не нашли это обращение."); return; } ctx.session.pendingTicketId = ctx.callbackQuery.data.split(":")[2]; ctx.session.step = "admin_ticket_reply"; await ctx.reply("Напишите ответ пользователю.", { reply_markup: { force_reply: true, input_field_placeholder: "Ответ" } }); });
composer.callbackQuery(/^admin:ticket:(.+):close$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const t = await findTicket(ctx, ctx.callbackQuery.data.split(":")[2]); if (!t) { await ctx.reply("Не нашли это обращение."); return; } t.status = "closed"; t.updated_at = now(); await saveTicket(ctx, t); try { await ctx.api.sendMessage(t.user_id, "Обращение закрыто. Если понадобится помощь, создайте новое."); } catch { /* blocked user */ } await ctx.reply("Обращение закрыто."); });

composer.callbackQuery("admin:users", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const list = (await users(ctx)).slice(0, 10); await ctx.reply(list.length ? "Пользователи:\n" + list.map((u) => `${u.display_name}${u.banned ? " · заблокирован" : ""}`).join("\n") : "Пользователей пока нет.", { reply_markup: inlineKeyboard([[inlineButton("⬅️ В панель", "admin:open")]]) }); });
composer.callbackQuery("admin:broadcast", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; ctx.session.step = "broadcast_message"; await ctx.reply("Отправьте текст рассылки для предпросмотра.", { reply_markup: { force_reply: true, input_field_placeholder: "Текст сообщения" } }); });
composer.callbackQuery("admin:broadcast:send", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await gate(ctx))) return; const text = ctx.session.pendingBroadcast; if (!text) { await ctx.reply("Текст рассылки не найден. Создайте её заново."); return; } let sent = 0; for (const u of await users(ctx)) { try { await ctx.api.sendMessage(u.telegram_id, text); sent++; } catch { /* continue after blocked users */ } } ctx.session.pendingBroadcast = undefined; ctx.session.step = "idle"; await ctx.reply(`Рассылка завершена. Доставлено: ${sent}.`); });

composer.on("message:text", async (ctx, next) => { if (ctx.session.step === "admin_product_form") { if (!(await gate(ctx))) return; const f = ctx.message.text.split("|").map((x) => x.trim()); if (f.length !== 6 || !Number.isFinite(Number(f[2])) || Number(f[2]) <= 0 || !/^https:\/\//i.test(f[5])) { await ctx.reply("Проверьте формат: 6 полей, цена больше нуля, ссылка начинается с https://."); return; } const old = ctx.session.pendingProductEditId ? (await products(ctx)).find((p) => p.id === ctx.session.pendingProductEditId) : undefined; const stamp = now(); const p: Product = { id: old?.id ?? `product-${stamp.replace(/\D/g, "").slice(-12)}`, name: f[0], description: f[1], price: Number(f[2]), currency: f[3], delivery_instructions: f[4], payment_link: f[5], active: true, created_at: old?.created_at ?? stamp, updated_at: stamp, admin_notes: [...(old?.admin_notes ?? []), `${old ? "updated" : "created"} ${stamp}`] }; await saveProduct(ctx, p); ctx.session.step = "idle"; ctx.session.pendingProductEditId = undefined; await ctx.reply("Товар сохранён.", { reply_markup: inlineKeyboard([[inlineButton("К товарам", "admin:products")]]) }); return; } if (ctx.session.step === "admin_ticket_reply") { if (!(await gate(ctx))) return; const t = ctx.session.pendingTicketId ? await findTicket(ctx, ctx.session.pendingTicketId) : undefined; if (!t) { await ctx.reply("Не нашли это обращение."); return; } t.admin_responses.push({ message: ctx.message.text, at: now() }); t.status = "waiting"; t.updated_at = now(); await saveTicket(ctx, t); try { await ctx.api.sendMessage(t.user_id, `Ответ поддержки:\n${ctx.message.text}`); } catch { /* blocked user */ } ctx.session.step = "idle"; ctx.session.pendingTicketId = undefined; await ctx.reply("Ответ отправлен."); return; } if (ctx.session.step === "broadcast_message") { if (!(await gate(ctx))) return; ctx.session.pendingBroadcast = ctx.message.text; ctx.session.step = "broadcast_confirm"; await ctx.reply(`Предпросмотр:\n\n${ctx.message.text}`, { reply_markup: inlineKeyboard([[inlineButton("✅ Подтвердить", "admin:broadcast:send")], [inlineButton("Отмена", "admin:open")]]) }); return; } return next(); });

export default composer;
